name: Docker Build and Push

on:
  push:
    paths:
      - 'vision.txt'
    branches:
      - main

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get version from vision.txt
        id: get-version
        run: |
          VERSION=$(cat vision.txt | tr -d '\n\r')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version is $VERSION"

  build-and-push:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 2328760190
          password: ${{ secrets.TOKEN }}
          
      - name: Build and push AMD64 image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/2328760190/imagine:${{ needs.get-version.outputs.version }}
            ghcr.io/2328760190/imagine:latest
          
      - name: Build and push ARM image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/2328760190/imagine-arm:${{ needs.get-version.outputs.version }}
            ghcr.io/2328760190/imagine-arm:latest
